### PR TITLE
Avoid reading time stamp counter

### LINKED ISSUE #1071: Antivirus dynamic shell code execution
### Environment

    NetMQ Version:    4.0.1.13
    Operating System: Windows 10
    .NET Version:     .Net 6

### Expected behavior
I would like to be able to have an option to force the NetMQ.Core.Utils.Clock's s_rdtscSupported to false, and therefore always fall back to using Stopwatch.GetTimestamp. As an idea add this Boolean:
```cs
public class SocketOptions
{
        /// <summary>
        /// If set, the time stamp counter is not read directly through opcode injection, rather
        /// <see cref="System.Diagnostics.Stopwatch.GetTimestamp"/> is used.
        /// </summary>
        public static bool DoNotUseRDTSC;
```
Then in Opcode.Open
```cs
        public static bool Open()
        {
            if (SocketOptions.DoNotUseRDTSC)
                return false;
```

### Actual behavior
 The method of injecting opcode into memory and invoking it to read the time stamp counter is being detected as dynamic shellcode by some anti-malware such as Sophos. When detected, the process executing the code is terminated. The detection as malware occurs when the Opcode.Open method is called and the s_codeBuffer is allocated with EXECUTE_READWRITE. 

### Steps to reproduce the behavior
Bind a publish socket to a tcp URL when running on a system protected by Sophos. Unfortunately, my companies corporate IT has deployed this feature everywhere and I can't argue it is able to detect actual malware scenarios. But I have a large engineering community where ZeroMQ is going to become more prevalent.

### PR DESCRIPTION
**Pull request by rickshaw5724**
The implementations using an environment variable rather than a static flag on an unrelated class.

Fixes #1071

### CODE REVIEW

File: src/NetMQ/Core/Utils/OpCode.cs [hunk 1]
```diff
@@ -11,6 +11,14 @@ internal static class Opcode
 
         public static bool Open()
         {
+            //Look for an environment variable: "NETQM_SUPPRESS_RDTSC" with a value of "TRUE"
+            // The application can set this environment variable when this code is running in a system where
+            // it is not desirable to read the processor's time stamp counter.
+            // While this is supported in modern CPUs, the technique used for allocating executable memory, copying OP Code
+            // for the read of the time stamp and invoking the OP Code can be detected as Malware by some anti-virus vendors.
```
Comment (drewnoakes) [inline src/NetMQ/Core/Utils/OpCode.cs:18]: Please include a link to the original issue here so that we can more easily see the motivation for this feature in future:

```suggestion
            // for the read of the time stamp and invoking the OP Code can be detected as Malware by some anti-virus vendors.
            // https://github.com/zeromq/netmq/issues/1071
```

File: src/NetMQ/Core/Utils/OpCode.cs [hunk 2]
```diff
@@ -11,6 +11,14 @@ internal static class Opcode
...
+            var val = Environment.GetEnvironmentVariable("NETQM_SUPPRESS_RDTSC");
+            if ("TRUE".Equals(val, StringComparison.OrdinalIgnoreCase))
+                return false;
```
Comment (drewnoakes) [inline src/NetMQ/Core/Utils/OpCode.cs:21]: What do you think about supporting any value in this environment variable? It's not uncommon to want to set a variable like this to `1`. We could just check for any non-`null` value.

```suggestion
            if (Environment.GetEnvironmentVariable("NETQM_SUPPRESS_RDTSC") is not null)
                return false;
```

Comment (drewnoakes) [reply src/NetMQ/Core/Utils/OpCode.cs:21]: The downside of this approach would be that setting the value to `false` would not do what you expect.

I'm happy with whatever you decide.

**Comment by rickshaw5724** [comment]
I made the change to use any value set to the environment variable as suggested and added a link to the github issue.
I'm a bit new to github, so I hope this commits that to this pull request

**Review by drewnoakes — APPROVED** [review]
Looks great, thanks very much!
